import Head from 'next/head'

import NavBar from '../../components/NavBar';
import Footer from '../../components/Footer';

import {StyledCampanhas, Artigo} from '../../styles/campanhas'

export default function Index(){
    return(
        <StyledCampanhas>
            <Head>
                <title>Grupo Rio - Campanhas</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <section>
                <NavBar/>
                <div>
                    <h1>Campanhas</h1>
                </div>
            </section>

            <section>
                <h2>Campanhas Passadas</h2>

                <div>
                    <Artigo img="/campanhas/a-liga-dos-super-vendedores/index.jpg">
                        <div>
                            <h3>A Liga dos Super Vendedores</h3>
                            <p>2014</p>
                        </div>

                        <div/>
                    </Artigo>

                    <Artigo img="/campanhas/bmg-folia/index.jpg">
                        <div>
                            <h3>BMG Folia</h3>
                            <p>2015</p>
                        </div>

                        <div/>
                    </Artigo>

                    <Artigo img="/campanhas/copa-do-mundo-bmg/index.jpg">
                        <div>
                            <h3>Copa do Mundo BMG</h3>
                            <p>2014</p>
                        </div>

                        <div/>
                    </Artigo>

                    <Artigo img="/campanhas/carnamar/index.jpg">
                        <div>
                            <h3>Carnamar BMG</h3>
                            <p>2014</p>
                        </div>

                        <div/>
                    </Artigo>

                    <Artigo img="/campanhas/mundo-magico/index.jpg">
                        <div>
                            <h3>Mundo Mágico</h3>
                            <p>2013</p>
                        </div>

                        <div/>
                    </Artigo>

                    <Artigo img="/campanhas/copa-do-mundo-2010/index.jpg">
                        <div>
                            <h3>Copa do Mundo BMG</h3>
                            <p>2010</p>
                        </div>

                        <div/>
                    </Artigo>
                </div>

            </section>

            <Footer/>
        </StyledCampanhas>
    )
}