import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import NavBar from '../components/NavBar'
import ApoiadoresSlider from '../components/ApoiadoresSlider'

import { StyledIndex } from '../styles'

const Home: NextPage = () => {
  return (
    <StyledIndex>
      <Head>
        <title>Grupo Rio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>

      <main>
        <NavBar/>
        <section>
          <Image src="/first-session/background.png" alt="background" width="1536px" height="864px" layout="responsive"/>
          <ApoiadoresSlider/>
        </section>
      </main>
    </StyledIndex>
  )
}

export default Home
